Harden isDart2 method.
I've just gotten this exception:

```
Skipped package: mockery (does not use flutter)
Skipped package: periodic_table (does not use flutter)
NoSuchMethodError: The method 'trim' was called on null.
Receiver: null
Tried calling: trim()
      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
      new VersionConstraint.parse.skipWhitespace (package:pub_semver/src/version_constraint.dart:51:19)
      new VersionConstraint.parse (package:pub_semver/src/version_constraint.dart:54:19)
      isDart2 (package:pub_crawl/src/filters.dart:6:23)
      FetchCommand._listPackages (package:pub_crawl/src/commands/fetch.dart:95:14)
<asynchronous suspension>
      FetchCommand.run (package:pub_crawl/src/commands/fetch.dart:38:26)
<asynchronous suspension>
      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
      Cli.run (package:pub_crawl/cli.dart:25:12)
<asynchronous suspension>
      main (file:///usr/local/google/home/dit/lib/pub_crawl/bin/pub_crawl.dart:4:15)
<asynchronous suspension>
      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```